### PR TITLE
Moved 'remove friend' to list of friends

### PR DESCRIPTION
**Pull request by marcus7777**
This makes It easier to use

### CODE REVIEW

**Comment by marcus7777** [comment]
For the Example Songr-Tutorial

**Comment by dxnn** [comment]
Hi Marcus, this is a good pull request -- would you mind making it on the dev branch instead of on master? We run everything through the dev branch first, and we'd be happy to accept it there.

**Comment by marcus7777** [comment]
Okay Cool

**Comment by marcus7777** [comment]
the dev branch brecks the demo, I get 
Uncaught ReferenceError: EB is not defined
songr.js:1 (anonymous function)

I think
 https://github.com/EveryBit-com/everybit.js/commit/03cb218f18dde210959bb7233b98e95796ed9198
fix this after 
https://github.com/EveryBit-com/everybit.js/issues/172
I put in the PR on dev anyway as it does not break more

**Pull request closed without merging**
